import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import type { AIRecommendation, MitigationRecommendation } from "@/types";

const descriptions: Record<string, string> = { "patch deployment": "Apply security updates to reduce known vulnerability exposure.", "access control tightening": "Reduce unnecessary privileges and strengthen authentication boundaries.", "network segmentation": "Isolate critical systems to limit lateral movement after compromise.", "additional monitoring": "Improve detection coverage and response visibility for risky activity." };
const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;

export function MitigationRecommendationsPanel({ recommendations, source }: { recommendations: (MitigationRecommendation | AIRecommendation)[]; source: "ai" | "mock" }) {
  const isAi = source === "ai";
  return <Card><CardHeader><CardTitle>Mitigation Recommendations</CardTitle><CardDescription>{isAi ? "AI-estimated — order-of-magnitude, not calculated" : "Structured actions from the investment recommendations register"}</CardDescription></CardHeader><CardContent>{recommendations.length === 0 ? <p className="risk-empty">No recommendations available yet.</p> : <div className="recommendation-list">{recommendations.map((recommendation) => <Card size="sm" className={`recommendation-card priority-level-${recommendation.priority}`} key={"recommendation_id" in recommendation ? recommendation.recommendation_id : `${recommendation.control_name}-${recommendation.priority}`}><article className="recommendation-item"><div className="recommendation-heading"><div><h3>{recommendation.control_name}</h3><p className="text-xs">{"description" in recommendation ? recommendation.description : descriptions[recommendation.control_name] || "Reduce exposure through a targeted security control."}</p></div><Badge variant="outline" className={recommendation.priority === 1 ? "border-[var(--danger)] bg-[var(--danger)] text-white" : recommendation.priority === 2 ? "border-[var(--warning)] bg-[#fff0df] text-[var(--warning)]" : "border-[#92751b] bg-[#fff8dc] text-[#92751b]"}>Priority {recommendation.priority}</Badge></div><div className="recommendation-metrics">{"investment_cost" in recommendation && <span className="text-xs">Investment <strong>{money(recommendation.investment_cost)}</strong></span>}<span className="text-xs">Risk reduction <strong>{recommendation.risk_reduction}%</strong></span><span className="text-xs">{isAi ? "ROI estimate" : "ROI"} <strong>{"roi_estimate" in recommendation ? recommendation.roi_estimate : `${recommendation.roi.toFixed(1)}x`}</strong></span></div></article></Card>)}</div>}</CardContent></Card>;}
