import { useMemo } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import type { RiskQuantificationSummary, TechnicalFindingRow } from "@/types";
import { LikelihoodImpactQuadrantChart } from "@/components/risk-analysis/likelihood-impact-quadrant-chart";
import { getRiskDrivers } from "@/lib/technical-dashboard/risk-drivers";

const money = (value?: number | null) => value == null ? "Pending" : `₹${value.toLocaleString("en-IN")}`;
const score = (value?: number | null) => value == null ? "Pending" : value.toFixed(2);

export function RiskQuantificationPanel({ summary, findings }: { summary: RiskQuantificationSummary; findings: TechnicalFindingRow[] }) {
  const drivers = useMemo(() => Array.from(new Set(findings.flatMap(getRiskDrivers))).slice(0, 5), [findings]);
  return <Card><CardHeader><CardTitle>Risk Quantification</CardTitle><CardDescription>{summary.asset_name} · {summary.business_unit || "Business unit pending"}</CardDescription></CardHeader><CardContent className="risk-panel-content"><Card size="sm" className="risk-section-card"><CardContent className="risk-score-grid"><div><span className="text-xs">Likelihood score</span><strong>{score(summary.likelihood_score)}</strong>{summary.likelihood_score == null && <small className="text-xs">Pending risk calculation</small>}</div><div><span className="text-xs">Impact score</span><strong>{score(summary.impact_score)}</strong>{summary.impact_score == null && <small className="text-xs">Pending risk calculation</small>}</div></CardContent></Card><Card size="sm" className="risk-section-card"><CardHeader><CardTitle className="text-sm">Financial exposure</CardTitle></CardHeader><CardContent><div className="risk-financial-section"><div className="risk-financial-grid"><div><span className="text-xs">Annual loss expectancy (ALE)</span><strong>{money(summary.ale)}</strong></div><div className="risk-estimate"><span className="text-xs">Value at Risk <em>(estimated)</em></span><strong>{money(summary.estimatedValueAtRisk)}</strong><small className="text-xs">Illustrative tail-loss estimate, not backend-calculated.</small></div></div></div></CardContent></Card><p className="risk-summary-line">{summary.ale == null ? "Risk calculation is pending." : `Based on current findings, this asset carries an estimated annual loss exposure of ${money(summary.ale)}.`}</p><div className="risk-context"><Badge variant="outline">Criticality {summary.criticality ?? "Pending"}</Badge><span>Asset value {money(summary.asset_value)}</span></div><div className="risk-analysis-additions"><LikelihoodImpactQuadrantChart summary={summary} /><Card size="sm"><CardHeader><CardTitle className="text-sm">Key Risk Drivers</CardTitle><CardDescription>Derived from finding and control data</CardDescription></CardHeader><CardContent>{drivers.length ? <ul className="risk-drivers-list">{drivers.map((driver) => <li key={driver}>{driver}</li>)}</ul> : <p className="risk-empty">No significant risk drivers identified</p>}</CardContent></Card></div></CardContent></Card>;
}
